FROM golang:1.13-alpine3.11 AS builder
RUN apk add --no-cache \
    git make gcc \
    gpgme-dev \
    go-md2man \
    glib-dev libc-dev
WORKDIR /app
COPY . .
RUN make BUILDTAGS='exclude_graphdriver_btrfs exclude_graphdriver_devicemapper' bin/skopeo

FROM alpine:latest
RUN apk add --no-cache ca-certificates

COPY --from=builder /app/bin/skopeo /usr/local/bin/skopeo
COPY --from=builder /app/default-policy.json /etc/containers/policy.json

ENTRYPOINT ["/usr/local/bin/skopeo"]
